# Generated by Django 4.1.5 on 2023-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%y/%m/%d')),
                ('club_name', models.CharField(max_length=10)),
                ('club_services', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_open_closed', models.TimeField()),
            ],
        ),
    ]
