# Generated by Django 4.1.5 on 2023-02-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='price',
            field=models.CharField(choices=[('50$', '50$'), ('100$', '100$'), ('200$', '200$'), ('300$', '300$')], max_length=300),
        ),
    ]
