# Generated by Django 4.1.5 on 2023-02-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='feature',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='price',
            field=models.CharField(choices=[('50$', '50$'), ('100$', '100$'), ('150$', '150$'), ('200$', '200$'), ('250$', '250$'), ('300$', '300$'), ('350$', '350$'), ('400$', '400$'), ('450$', '450$')], max_length=300),
        ),
    ]
