# Generated by Django 4.1.5 on 2023-02-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_club_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='time_open_closed',
        ),
    ]
