# Generated by Django 4.1.5 on 2023-02-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default="{% static 'images/defult.jpg'%}", upload_to='images/%y/%m/%d'),
        ),
    ]
