# Generated by Django 4.1.5 on 2023-02-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
