# Generated by Django 4.1.5 on 2023-02-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_contact_user_contact_email_contact_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
