# Generated by Django 4.1.5 on 2023-02-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
