# Generated by Django 4.1.5 on 2023-02-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
