# Generated by Django 4.1.5 on 2023-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_contactform_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='images/defult.jpg', upload_to='profile_pic'),
        ),
    ]
