# Generated by Django 4.1.5 on 2023-02-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_booking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
    ]
